name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.42.5
        with:
          token: ${{ github.token }}
          command: site
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/__sapper__/export
      - id: deploy
        uses: actions/deploy-pages@v4
